version: '2'
services:
  web:
    container_name: b-me-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/opt/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true